import { assert } from "node:console";
import * as fs from "node:fs";
import * as path from "node:path";

const wasmsPaths = path.resolve(__dirname, "../wasm");
const wasmsNames = fs.readdirSync(wasmsPaths);

const convertFileContent = (base64) => `
  /* Autogenerated file. Do not edit manually. */
  /* eslint-disable eslint-comments/disable-enable-pair */
  /* eslint-disable eslint-comments/no-unlimited-disable */
  /* eslint-disable */
  /* prettier-ignore */
  const base64 = "${base64}";
  const wasm = new Uint8Array(Buffer.from(base64, 'base64'));
  export default wasm;
`;

wasmsNames.forEach(async fileName => {
  const orgFileContent = fs.readFileSync(path.resolve(__dirname, `../wasm/${fileName}`));
  const convertedFileContent = convertFileContent(orgFileContent);
  const savedFilePath = path.resolve(__dirname, `../wasm/${fileName}.ts`);
  await fs.writeFileSync(savedFilePath, convertedFileContent);
});



// // eslint-disable-next-line import/first
// import generatedwasm from "../wasm";

// assert(wasm.length === generatedwasm.length, "Generated data mismatched");

// if (wasm.length !== generatedwasm.length) {
//   process.exit(-1);
// }
