import fs from 'node:fs';
import path from 'node:path';
declare const __dirname: string;

const LIST_OF_WASMS = [
  'cep78.wasm',
  'mint_session.wasm',
  'balance_of_session.wasm',
  'owner_of_session.wasm',
  'get_approved_session.wasm',
  'transfer_session.wasm',
  'updated_receipts.wasm',
  'is_approved_for_all_session.wasm',
];

const PATH_FROM = path.resolve(
  __dirname,
  '../../../target/wasm32-unknown-unknown/release'
);
const PATH_TO = path.resolve(__dirname, '../wasm');

const convertFileContent = (base64: string) => `
  /* Autogenerated file. Do not edit manually. */

  import { Buffer } from 'buffer';

  function base64ToUint8Array(base64: string) {
    return new Uint8Array(Buffer.from(base64, 'base64'));
  }

  const base64 = "${base64}";
  const wasm = base64ToUint8Array(base64);
  export default wasm;
`;

const runConversion = async () => {
  fs.rmSync(PATH_TO, { recursive: true, force: true });
  fs.mkdirSync(PATH_TO);

  LIST_OF_WASMS.forEach(async (fileName) => {
    const orgFileContent = fs.readFileSync(
      path.resolve(__dirname, `${PATH_FROM}/${fileName}`)
    );
    const base64 = orgFileContent.toString('base64');
    const convertedFileContent = convertFileContent(base64);
    const savedFilePath = path.resolve(
      __dirname,
      `../wasm/${fileName.split('.')[0]}.ts`
    );
    fs.writeFileSync(savedFilePath, convertedFileContent);
  });
  // eslint-disable-next-line no-console
  console.info('Copy and convert done.');
};

runConversion();
