name: ci-cep-78-enhanced-nft-to-remove

on:
  push:
    branches: [dev, feat-*, release-*]

  pull_request:
    branches: [dev, feat-*, release-*]

jobs:
  # This build step shall be removed, only for PR passing previous CI/CD checks
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
      - run: sudo apt update && sudo apt install -y build-essential wabt
      - uses: Swatinem/rust-cache@v2
      - run: make build-all-contracts
